/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactRecord {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface VisitStats {
  'dailyVisits' : Array<[bigint, bigint]>,
  'totalVisits' : bigint,
  'visitsByCity' : Array<[string, bigint]>,
}
export interface _SERVICE {
  'deleteContact' : ActorMethod<[bigint], boolean>,
  'getAllContacts' : ActorMethod<[], Array<ContactRecord>>,
  'getContact' : ActorMethod<[bigint], [] | [ContactRecord]>,
  'getVisitStats' : ActorMethod<[], VisitStats>,
  'recordVisit' : ActorMethod<[string], undefined>,
  'removeContact' : ActorMethod<[bigint], boolean>,
  'submitContact' : ActorMethod<[string, string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];