/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactRecord = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const VisitStats = IDL.Record({
  'dailyVisits' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Nat)),
  'totalVisits' : IDL.Nat,
  'visitsByCity' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});

export const idlService = IDL.Service({
  'deleteContact' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactRecord)], ['query']),
  'getContact' : IDL.Func([IDL.Nat], [IDL.Opt(ContactRecord)], ['query']),
  'getVisitStats' : IDL.Func([], [VisitStats], ['query']),
  'recordVisit' : IDL.Func([IDL.Text], [], []),
  'removeContact' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactRecord = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const VisitStats = IDL.Record({
    'dailyVisits' : IDL.Vec(IDL.Tuple(IDL.Int, IDL.Nat)),
    'totalVisits' : IDL.Nat,
    'visitsByCity' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  
  return IDL.Service({
    'deleteContact' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactRecord)], ['query']),
    'getContact' : IDL.Func([IDL.Nat], [IDL.Opt(ContactRecord)], ['query']),
    'getVisitStats' : IDL.Func([], [VisitStats], ['query']),
    'recordVisit' : IDL.Func([IDL.Text], [], []),
    'removeContact' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };